blueprint:
  name: Leak detection & notification
  description: Send a notification when any configured moisture sensor becomes moist
  domain: automation
  input:
    excluded_sensors:
      name: Excluded Sensors
      description: Sensors to exclude from leak detection (e.g., rain sensors). Use entity IDs.
      default: []
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: moisture
          multiple: true
    actions:
      name: Actions
      description: Notifications or similar to be run. Use {{ trigger.event.data.new_state.attributes.friendly_name
        }} in a message for a friendly name of the sensor.
      selector:
        action: {}
  source_url: https://gist.github.com/TurtleFX/213bd28f5cfb1a7cded5eb2e91aa30b8
trigger:
- event_data: {}
  event_type: state_changed
  platform: event
condition:
- condition: template
  value_template: '{{ trigger.event.data.new_state.attributes.device_class == "moisture"
    }}'
- condition: template
  value_template: '{{ trigger.event.data.new_state.state == "on" }}'
- condition: template
  value_template: '{{ trigger.event.data.entity_id not in excluded_sensors }}'
action:
- choose: []
  default: !input actions
mode: single
