blueprint:
  name: Leak detection & notification
  description: Send a notification when any selected moisture sensor becomes moist
  domain: automation
  input:
    moisture_sensors:
      name: Moisture Sensors
      description: Moisture sensors to monitor for leaks
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: moisture
          multiple: true

    actions:
      name: Actions
      description: >
        Notifications or similar to be run.
        Use {{ trigger.to_state.name }} in a message
        for a friendly name of the sensor.
      selector:
        action: {}

trigger:
  # Only these selected moisture sensors
  - platform: state
    entity_id: !input moisture_sensors
    from: "off"
    to: "on"

condition:
  - condition: template
    value_template: >
      {{ trigger is defined
         and trigger.to_state is defined
         and trigger.to_state.attributes.device_class == 'moisture' }}

  - condition: template
    value_template: >
      {{ trigger is defined
         and trigger.to_state is defined
         and trigger.to_state.state == 'on' }}


action:
  - choose: []
    default: !input actions

mode: single
