blueprint:
  name: Leak detection & notification
  description: Send a notification when any configured moisture sensor becomes moist
  domain: automation
  input:
    excluded_sensors:
      name: Excluded Sensors
      description: Moisture sensors to exclude from leak detection (e.g., outdoor rain sensors)
      default: []
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: moisture
          multiple: true
    actions:
      name: Actions
      description: Notifications or similar to be run. Use {{ trigger.event.data.new_state.attributes.friendly_name
        }} in a message for a friendly name of the sensor.
      selector:
        action: {}
trigger:
- event_data: {}
  event_type: state_changed
  platform: event
condition:
- condition: template
  value_template: '{{ trigger.event.data.new_state.attributes.device_class == "moisture"
    }}'
- condition: template
  value_template: '{{ trigger.event.data.new_state.state == "on" }}'
- condition: template
  value_template: >
    {% set excluded = excluded_sensors %}
    {{ trigger.event.data.entity_id not in excluded }}
action:
- choose: []
  default: !input actions
mode: single
