blueprint:
  name: Leak Detector Notifier
  description: >
    Send notifications when leak sensors detect moisture, with the ability to exclude specific sensors (e.g., rain sensors).
  domain: automation
  input:
    leak_sensors:
      name: Leak Sensors
      description: Select the leak sensors to monitor
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: moisture
          multiple: true
    excluded_sensors:
      name: Excluded Sensors
      description: Select sensors to exclude from leak detection (e.g., rain sensors)
      default: []
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: moisture
          multiple: true
    notification_service:
      name: Notification Service
      description: The notification service to use (e.g., notify.mobile_app_your_phone)
      selector:
        text:
    notification_title:
      name: Notification Title
      description: Title for the notification
      default: "Leak Detected!"
      selector:
        text:
    notification_message:
      name: Notification Message
      description: Message for the notification. Use {{trigger.to_state.attributes.friendly_name}} for sensor name.
      default: "Water leak detected by {{trigger.to_state.attributes.friendly_name}}"
      selector:
        text:
          multiline: true

trigger:
  - platform: state
    entity_id: !input leak_sensors
    to: "on"

condition:
  - condition: template
    value_template: >
      {% set excluded = excluded_sensors %}
      {{ trigger.entity_id not in excluded }}

action:
  - service: !input notification_service
    data:
      title: !input notification_title
      message: !input notification_message

mode: queued
max: 10
